name: First Workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display some text
        run: echo "Some text"
      - name: Command in Multiline
        run: |
          pip list
      - name: Install Pillow
        run:
          pip install pillow